<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5qGI5L6L');
$cfg_Cs[2]=array(1,1,1,'6K6+6K6h5qGI5L6L');
$cfg_Cs[3]=array(1,1,1,'5pGE5b2x5qGI5L6L');
$cfg_Cs[4]=array(1,1,1,'5rS75Yqo562W5YiS5qGI5L6L');
$cfg_Cs[5]=array(0,1,1,'5LqG6Kej5pu05aSa');
$cfg_Cs[6]=array(5,1,1,'5pyN5Yqh5rWB56iL');
$cfg_Cs[7]=array(5,1,1,'5YWz5LqO5oiR5Lus5aSn5LqL5Lu2');
$cfg_Cs[8]=array(0,1,1,'6IGU57O75oiR5Lus');
?>