<div class="uk-panel uk-width-medium-1-3 textAlignLeft ">
							<div class="uk-panel border pb18">
								<a href="[field:arcurl/]"><img class="tm-image-pull" src="[field:litpic/]" alt="[field:title/]" width="380px" height="260px"  style="height:260px"/></a>
								<p class="mt27 pl25">[field:pubdate function="MyDate('Y.m.d',@me)"/]</p>
								<h2 class="tm-article-subtitle pl25 font18px mt12">[field:title/]</h2>
							</div>
						</div>