<div class="uk-width-large-1-3 uk-width-small-1-1 textAlignLeft">
                <div class="uk-panel border pb18 bgcolorwhite mxwidth382">
					<a href="[field:arcurl/]"><img src="[field:litpic/]" width="100%"/></a>
                    <p class="mt27 pl25">[field:pubdate function="MyDate('Y.m.d',@me)"/]</p>
					<h2 class="tm-article-subtitle pl25">[field:title/]</h2>
                </div>
            </div>