<?php
$z[0]=Array("global","",453,482);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",561,590);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",659,688);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",754,783);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",844,873);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",938,967);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",1046,1075);
$z[6][4]['name']="cfg_templeturl";

?>