<?php
$z[0]=Array("field","",187,206);
$z[0][4]['name']="title";
$z[1]=Array("global","",207,233);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1261,1300);
$z[2][4]['filename']="res_nav.html";
$z[3]=Array("list","\r\n				<div class=\"uk-width-medium-1-3 textAlignLeft \">\r\n                    <div class=\"uk-panel border pb18\">\r\n                        <a href=\"[field:arcurl/]\"><img class=\"tm-image-pull\" src=\"{@me['litpic']}\" alt=\"Components\"/></a>\r\n                        <p class=\"mt27 pl25\">[field:pubdate function=\"MyDate('Y.m.d',@me)\"/]</p>\r\n						<h2 class=\"tm-article-subtitle pl25\">[field:title/]</h2>\r\n                    </div>\r\n                </div>\r\n				",1683,2172);
$z[3][4]['pagesize']="3";
$z[4]=Array("pagelist","",2229,2289);
$z[4][4]['listitem']="end,pre,next,pageno";
$z[4][4]['listsize']="5";
$z[5]=Array("include","",2347,2394);
$z[5][4]['filename']="res_contactinfo.html";

?>