<?php
$z[0]=Array("field","",182,201);
$z[0][4]['name']="title";
$z[1]=Array("global","",202,228);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",279,309);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",345,372);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",1378,1417);
$z[4][4]['filename']="res_nav.html";
$z[5]=Array("list","\n				<div class=\"uk-panel uk-width-medium-1-3 textAlignLeft \">\n                    <div class=\"uk-panel border pb18\">\n                        <a href=\"[field:arcurl/]\"><img class=\"tm-image-pull\" src=\"[field:litpic/]\" alt=\"Components\"/></a>\n                        <p class=\"mt27 pl25\">[field:pubdate function=\"MyDate('Y.m.d',@me)\"/]</p>\n						<h2 class=\"tm-article-subtitle pl25\">[field:title/]</h2>\n                    </div>\n                </div>\n				",1793,2283);
$z[5][4]['pagesize']="9";
$z[6]=Array("pagelist","",2337,2397);
$z[6][4]['listitem']="end,pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2451,2498);
$z[7][4]['filename']="res_contactinfo.html";

?>