<?php
$z[0]=Array("global","",131,161);
$z[0][4]['name']="cfg_description";
$z[1]=Array("global","",197,224);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",322,348);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",1354,1393);
$z[3][4]['filename']="res_nav.html";
$z[4]=Array("include","",5100,5147);
$z[4][4]['filename']="res_contactinfo.html";
$z[5]=Array("arclist","\n			<div class=\"uk-width-large-1-3 uk-width-small-1-1 textAlignLeft pl30\">\n                <div class=\"uk-panel border pb18 bgcolorwhite mxwidth382\">\n					<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"380px\" height=\"260px\" style=\"height:260px\"/></a>\n                    <p class=\"mt27 pl25\">[field:pubdate function=\"MyDate('Y.m.d',@me)\"/]</p>\n					<h2 class=\"tm-article-subtitle pl25 font18px mt12\">[field:title/]</h2>\n                </div>\n            </div>\n			",5418,5943);
$z[5][4]['typeid']="1";
$z[5][4]['row']="6";
$z[6]=Array("global","",7136,7162);
$z[6][4]['name']="cfg_powerby";

?>