<?php
$z[0]=Array("field","",182,201);
$z[0][4]['name']="title";
$z[1]=Array("global","",202,228);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",273,296);
$z[2][4]['name']="seotitle";
$z[3]=Array("global","",334,361);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",1367,1406);
$z[4][4]['filename']="res_nav.html";
$z[5]=Array("arclist","\n						<div class=\"uk-panel uk-width-medium-1-3 textAlignLeft \">\n							<div class=\"uk-panel border pb18\">\n								<a href=\"[field:arcurl/]\"><img class=\"tm-image-pull\" src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"380px\" height=\"260px\"  style=\"height:260px\"/></a>\n								<p class=\"mt27 pl25\">[field:pubdate function=\"MyDate('Y.m.d',@me)\"/]</p>\n								<h2 class=\"tm-article-subtitle pl25 font18px mt12\">[field:title/]</h2>\n							</div>\n						</div>\n					",1799,2307);
$z[5][4]['typeid']="2";
$z[5][4]['row']="3";
$z[6]=Array("arclist","\n						<div class=\"uk-panel uk-width-medium-1-3 textAlignLeft \">\n							<div class=\"uk-panel border pb18\">\n								<a href=\"[field:arcurl/]\"><img class=\"tm-image-pull\" src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"380px\" height=\"260px\"/></a>\n								<p class=\"mt27 pl25\">[field:pubdate function=\"MyDate('Y.m.d',@me)\"/]</p>\n								<h2 class=\"tm-article-subtitle pl25 font18px mt12\">[field:title/]</h2>\n							</div>\n						</div>\n					",2636,3122);
$z[6][4]['typeid']="3";
$z[6][4]['row']="3";
$z[7]=Array("arclist","\n				<div class=\"uk-panel uk-width-medium-1-3 textAlignLeft \">\n                    <div class=\"uk-panel border pb18\">\n                        <a href=\"[field:arcurl/]\"><img class=\"tm-image-pull\" src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"380px\" height=\"260px\"/></a>\n                        <p class=\"mt27 pl25\">[field:pubdate function=\"MyDate('Y.m.d',@me)\"/]</p>\n						<h2 class=\"tm-article-subtitle pl25 font18px mt12\">[field:title/]</h2>\n                    </div>\n                </div>\n			        ",3453,4009);
$z[7][4]['typeid']="4";
$z[7][4]['row']="3";
$z[8]=Array("include","",4098,4145);
$z[8][4]['filename']="res_contactinfo.html";
$z[9]=Array("global","",4287,4313);
$z[9][4]['name']="cfg_powerby";

?>