<?php
$z[0]=Array("field","",182,201);
$z[0][4]['name']="title";
$z[1]=Array("global","",202,228);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",279,302);
$z[2][4]['name']="seotitle";
$z[3]=Array("global","",340,367);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",1373,1412);
$z[4][4]['filename']="res_nav.html";
$z[5]=Array("field","",1702,1721);
$z[5][4]['name']="title";
$z[6]=Array("field","",1759,1784);
$z[6][4]['name']="description";
$z[7]=Array("list","\n				<div class=\"uk-panel uk-width-medium-1-3 textAlignLeft \">\n                    <div class=\"uk-panel border pb18\">\n                        <a href=\"[field:arcurl/]\"><img class=\"tm-image-pull\" src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"380px\" height=\"260px\" style=\"height:260px\"/></a>\n                        <p class=\"mt27 pl25\">[field:pubdate function=\"MyDate('Y.m.d',@me)\"/]</p>\n						<h2 class=\"tm-article-subtitle pl25 font18px mt12\">[field:title/]</h2>\n                    </div>\n                </div>\n				",1816,2374);
$z[7][4]['pagesize']="9";
$z[8]=Array("pagelist","",2428,2488);
$z[8][4]['listitem']="end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2542,2589);
$z[9][4]['filename']="res_contactinfo.html";
$z[10]=Array("global","",2731,2757);
$z[10][4]['name']="cfg_powerby";

?>