<?php  exit();
/*
Page: /dede/login.php
Error: 无法使用数据库
Time2015-12-16 21:21:55
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: No database selected <br />Error sql: <font color='red'>SELECT admin.*,atype.purviews FROM `dede_admin` admin LEFT JOIN `dede_admintype` atype ON atype.rank=admin.usertype WHERE admin.userid LIKE 'admin' LIMIT 0,1</font>
Time2015-12-16 21:21:55
*/
?>
<?php  exit();
/*
Page: /dede/index.php
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2015-12-16 21:24:55
*/
?>
<?php  exit();
/*
Page: /dede/index.php
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2015-12-16 21:24:56
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2015-12-16 21:24:57
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT arc.id, arc.arcrank, arc.title, arc.channel, ch.editcon  FROM `dede_archives` arc
            LEFT JOIN `dede_channeltype` ch ON ch.id = arc.channel
             WHERE arc.arcrank<>-2 ORDER BY arc.id DESC LIMIT 0, 6 </font>
Time2015-12-16 21:24:57
*/
?>
<?php  exit();
/*
Page: /dede/index_menu.php
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2015-12-16 21:24:58
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2015-12-16 21:25:00
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id, typename FROM `dede_channeltype` </font>
Time2015-12-16 21:25:00
*/
?>
<?php  exit();
/*
Page: /plus/list.php?tid=1
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT ch.issystem FROM `dede_arctype` tp LEFT JOIN `dede_channeltype` ch ON ch.id=tp.channeltype WHERE tp.id='1' LIMIT 0,1;</font>
Time2015-12-16 21:25:12
*/
?>
<?php  exit();
/*
Page: /plus/list.php?tid=1
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT tp.*,ch.typename as ctypename,ch.addtable,ch.issystem FROM `dede_arctype` tp left join `dede_channeltype` ch
        on ch.id=tp.channeltype  WHERE tp.id='1' LIMIT 0,1;</font>
Time2015-12-16 21:25:12
*/
?>
<?php  exit();
/*
Page: /plus/list.php?tid=1
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT ch.issystem FROM `dede_arctype` tp LEFT JOIN `dede_channeltype` ch ON ch.id=tp.channeltype WHERE tp.id='1' LIMIT 0,1;</font>
Time2015-12-16 21:25:13
*/
?>
<?php  exit();
/*
Page: /plus/list.php?tid=1
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT tp.*,ch.typename as ctypename,ch.addtable,ch.issystem FROM `dede_arctype` tp left join `dede_channeltype` ch
        on ch.id=tp.channeltype  WHERE tp.id='1' LIMIT 0,1;</font>
Time2015-12-16 21:25:13
*/
?>
<?php  exit();
/*
Page: /dede/
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2015-12-16 21:31:04
*/
?>
<?php  exit();
/*
Page: /dede/
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2015-12-16 21:31:05
*/
?>
<?php  exit();
/*
Page: /dede/index_menu.php
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2015-12-16 21:31:07
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2015-12-16 21:31:08
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT arc.id, arc.arcrank, arc.title, arc.channel, ch.editcon  FROM `dede_archives` arc
            LEFT JOIN `dede_channeltype` ch ON ch.id = arc.channel
             WHERE arc.arcrank<>-2 ORDER BY arc.id DESC LIMIT 0, 6 </font>
Time2015-12-16 21:31:08
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2015-12-16 21:31:09
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id, typename FROM `dede_channeltype` </font>
Time2015-12-16 21:31:09
*/
?>
<?php  exit();
/*
Page: /dede/
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2015-12-16 21:32:19
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2015-12-16 21:32:20
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT arc.id, arc.arcrank, arc.title, arc.channel, ch.editcon  FROM `dede_archives` arc
            LEFT JOIN `dede_channeltype` ch ON ch.id = arc.channel
             WHERE arc.arcrank<>-2 ORDER BY arc.id DESC LIMIT 0, 6 </font>
Time2015-12-16 21:32:20
*/
?>
<?php  exit();
/*
Page: /dede/index_menu.php
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2015-12-16 21:32:21
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2015-12-16 21:32:24
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id, typename FROM `dede_channeltype` </font>
Time2015-12-16 21:32:24
*/
?>
<?php  exit();
/*
Page: /dede/
Error: Table 'mili.dede_arctype' doesn't exist <br />Error sql: <font color='red'> SELECT channeltype FROM `dede_arctype` GROUP BY channeltype </font>
Time2015-12-16 21:36:17
*/
?>
<?php  exit();
/*
Page: /dede/
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2015-12-16 21:36:17
*/
?>
<?php  exit();
/*
Page: /dede/
Error: Table 'mili.dede_plus' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_plus` WHERE isshow=1 ORDER BY aid ASC</font>
Time2015-12-16 21:36:17
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_plus_seoinfo' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_plus_seoinfo` ORDER BY id DESC LIMIT 0,1;</font>
Time2015-12-16 21:36:19
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2015-12-16 21:36:19
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_arctiny' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_arctiny` LIMIT 0,1;</font>
Time2015-12-16 21:36:19
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_archives' doesn't exist <br />Error sql: <font color='red'>SELECT arc.id, arc.arcrank, arc.title, arc.channel, ch.editcon  FROM `dede_archives` arc
            LEFT JOIN `dede_channeltype` ch ON ch.id = arc.channel
             WHERE arc.arcrank<>-2 ORDER BY arc.id DESC LIMIT 0, 6 </font>
Time2015-12-16 21:36:19
*/
?>
<?php  exit();
/*
Page: /dede/index_menu.php
Error: Table 'mili.dede_arctype' doesn't exist <br />Error sql: <font color='red'> SELECT channeltype FROM `dede_arctype` GROUP BY channeltype </font>
Time2015-12-16 21:36:20
*/
?>
<?php  exit();
/*
Page: /dede/index_menu.php
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2015-12-16 21:36:20
*/
?>
<?php  exit();
/*
Page: /dede/index_testenv.php
Error: Table 'mili.dede_admin' doesn't exist <br />Error sql: <font color='red'>SELECT usertype,userid,pwd FROM dede_admin WHERE `userid`='admin' LIMIT 0,1;</font>
Time2015-12-16 21:36:21
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2015-12-16 21:36:22
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_feedback' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_feedback` LIMIT 0,1;</font>
Time2015-12-16 21:36:22
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id, typename FROM `dede_channeltype` </font>
Time2015-12-16 21:36:22
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_arctiny' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(channel) AS dd, channel FROM `dede_arctiny` GROUP BY channel </font>
Time2015-12-16 21:36:22
*/
?>
<?php  exit();
/*
Page: /dede/catalog_main.php
Error: Table 'mili.dede_arctype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typedir,typename,ispart,sortrank,ishidden FROM `dede_arctype` WHERE reid=0 order by sortrank</font>
Time2015-12-16 21:36:23
*/
?>
<?php  exit();
/*
Page: /dede/
Error: Table 'mili.dede_arctype' doesn't exist <br />Error sql: <font color='red'> SELECT channeltype FROM `dede_arctype` GROUP BY channeltype </font>
Time2015-12-16 21:41:43
*/
?>
<?php  exit();
/*
Page: /dede/
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2015-12-16 21:41:43
*/
?>
<?php  exit();
/*
Page: /dede/
Error: Table 'mili.dede_plus' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_plus` WHERE isshow=1 ORDER BY aid ASC</font>
Time2015-12-16 21:41:43
*/
?>
<?php  exit();
/*
Page: /dede/index_menu.php
Error: Table 'mili.dede_arctype' doesn't exist <br />Error sql: <font color='red'> SELECT channeltype FROM `dede_arctype` GROUP BY channeltype </font>
Time2015-12-16 21:41:45
*/
?>
<?php  exit();
/*
Page: /dede/index_menu.php
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2015-12-16 21:41:45
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_plus_seoinfo' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_plus_seoinfo` ORDER BY id DESC LIMIT 0,1;</font>
Time2015-12-16 21:41:46
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2015-12-16 21:41:46
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_arctiny' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_arctiny` LIMIT 0,1;</font>
Time2015-12-16 21:41:46
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'mili.dede_archives' doesn't exist <br />Error sql: <font color='red'>SELECT arc.id, arc.arcrank, arc.title, arc.channel, ch.editcon  FROM `dede_archives` arc
            LEFT JOIN `dede_channeltype` ch ON ch.id = arc.channel
             WHERE arc.arcrank<>-2 ORDER BY arc.id DESC LIMIT 0, 6 </font>
Time2015-12-16 21:41:46
*/
?>
<?php  exit();
/*
Page: /dede/index_testenv.php
Error: Table 'mili.dede_admin' doesn't exist <br />Error sql: <font color='red'>SELECT usertype,userid,pwd FROM dede_admin WHERE `userid`='admin' LIMIT 0,1;</font>
Time2015-12-16 21:41:47
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2015-12-16 21:41:48
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_feedback' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_feedback` LIMIT 0,1;</font>
Time2015-12-16 21:41:48
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id, typename FROM `dede_channeltype` </font>
Time2015-12-16 21:41:48
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'mili.dede_arctiny' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(channel) AS dd, channel FROM `dede_arctiny` GROUP BY channel </font>
Time2015-12-16 21:41:48
*/
?>
